// Generated by gencpp from file a53095838_assignment_4/cmd.msg
// DO NOT EDIT!


#ifndef A53095838_ASSIGNMENT_4_MESSAGE_CMD_H
#define A53095838_ASSIGNMENT_4_MESSAGE_CMD_H

#include <ros/service_traits.h>


#include <a53095838_assignment_4/cmdRequest.h>
#include <a53095838_assignment_4/cmdResponse.h>


namespace a53095838_assignment_4
{

struct cmd
{

typedef cmdRequest Request;
typedef cmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct cmd
} // namespace a53095838_assignment_4


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::a53095838_assignment_4::cmd > {
  static const char* value()
  {
    return "0e3bb1977c0401bcd0b9d7f3bcbaee05";
  }

  static const char* value(const ::a53095838_assignment_4::cmd&) { return value(); }
};

template<>
struct DataType< ::a53095838_assignment_4::cmd > {
  static const char* value()
  {
    return "a53095838_assignment_4/cmd";
  }

  static const char* value(const ::a53095838_assignment_4::cmd&) { return value(); }
};


// service_traits::MD5Sum< ::a53095838_assignment_4::cmdRequest> should match 
// service_traits::MD5Sum< ::a53095838_assignment_4::cmd > 
template<>
struct MD5Sum< ::a53095838_assignment_4::cmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::a53095838_assignment_4::cmd >::value();
  }
  static const char* value(const ::a53095838_assignment_4::cmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::a53095838_assignment_4::cmdRequest> should match 
// service_traits::DataType< ::a53095838_assignment_4::cmd > 
template<>
struct DataType< ::a53095838_assignment_4::cmdRequest>
{
  static const char* value()
  {
    return DataType< ::a53095838_assignment_4::cmd >::value();
  }
  static const char* value(const ::a53095838_assignment_4::cmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::a53095838_assignment_4::cmdResponse> should match 
// service_traits::MD5Sum< ::a53095838_assignment_4::cmd > 
template<>
struct MD5Sum< ::a53095838_assignment_4::cmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::a53095838_assignment_4::cmd >::value();
  }
  static const char* value(const ::a53095838_assignment_4::cmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::a53095838_assignment_4::cmdResponse> should match 
// service_traits::DataType< ::a53095838_assignment_4::cmd > 
template<>
struct DataType< ::a53095838_assignment_4::cmdResponse>
{
  static const char* value()
  {
    return DataType< ::a53095838_assignment_4::cmd >::value();
  }
  static const char* value(const ::a53095838_assignment_4::cmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // A53095838_ASSIGNMENT_4_MESSAGE_CMD_H
