// Generated by gencpp from file a53095838_assignment_4/cmdRequest.msg
// DO NOT EDIT!


#ifndef A53095838_ASSIGNMENT_4_MESSAGE_CMDREQUEST_H
#define A53095838_ASSIGNMENT_4_MESSAGE_CMDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace a53095838_assignment_4
{
template <class ContainerAllocator>
struct cmdRequest_
{
  typedef cmdRequest_<ContainerAllocator> Type;

  cmdRequest_()
    : processing_mode(0)
    , visual_mode(0)  {
    }
  cmdRequest_(const ContainerAllocator& _alloc)
    : processing_mode(0)
    , visual_mode(0)  {
    }



   typedef int8_t _processing_mode_type;
  _processing_mode_type processing_mode;

   typedef int8_t _visual_mode_type;
  _visual_mode_type visual_mode;




  typedef boost::shared_ptr< ::a53095838_assignment_4::cmdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::a53095838_assignment_4::cmdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct cmdRequest_

typedef ::a53095838_assignment_4::cmdRequest_<std::allocator<void> > cmdRequest;

typedef boost::shared_ptr< ::a53095838_assignment_4::cmdRequest > cmdRequestPtr;
typedef boost::shared_ptr< ::a53095838_assignment_4::cmdRequest const> cmdRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::a53095838_assignment_4::cmdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::a53095838_assignment_4::cmdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace a53095838_assignment_4

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::a53095838_assignment_4::cmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::a53095838_assignment_4::cmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::a53095838_assignment_4::cmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::a53095838_assignment_4::cmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::a53095838_assignment_4::cmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::a53095838_assignment_4::cmdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::a53095838_assignment_4::cmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2868f204a047becc6c5862b92299816f";
  }

  static const char* value(const ::a53095838_assignment_4::cmdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2868f204a047beccULL;
  static const uint64_t static_value2 = 0x6c5862b92299816fULL;
};

template<class ContainerAllocator>
struct DataType< ::a53095838_assignment_4::cmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a53095838_assignment_4/cmdRequest";
  }

  static const char* value(const ::a53095838_assignment_4::cmdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::a53095838_assignment_4::cmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 processing_mode\n\
int8 visual_mode\n\
";
  }

  static const char* value(const ::a53095838_assignment_4::cmdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::a53095838_assignment_4::cmdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.processing_mode);
      stream.next(m.visual_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct cmdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::a53095838_assignment_4::cmdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::a53095838_assignment_4::cmdRequest_<ContainerAllocator>& v)
  {
    s << indent << "processing_mode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.processing_mode);
    s << indent << "visual_mode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.visual_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // A53095838_ASSIGNMENT_4_MESSAGE_CMDREQUEST_H
